import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('dashboard filters traffic, exports CSV and navigates', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Обзор расходов.' })).toBeVisible()
  await expect(page.getByText('DEMO', { exact: true })).toBeVisible()
  const keyUsage = page.locator('.team-panel')
  await expect(keyUsage.getByRole('columnheader', { name: 'Виртуальный ключ / создан' })).toBeVisible()
  await expect(keyUsage.getByRole('columnheader', { name: 'Последнее использование, UTC' })).toBeVisible()
  await expect(keyUsage.getByText(/запросов/).first()).toBeVisible()
  await expect(keyUsage.getByText(/токенов/).first()).toBeVisible()
  await page.getByLabel('Период', { exact: true }).selectOption('7')
  await page.getByRole('button', { name: 'История запросов', exact: true }).click()
  await page.getByLabel('Провайдер', { exact: true }).selectOption('anthropic')
  await page.getByLabel('Статус запроса', { exact: true }).selectOption('success')
  await expect(page.locator('tbody tr').first()).toContainText('Claude')
  await expect(page.locator('tbody tr').first()).toContainText('Успешно')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Экспорт', exact: true }).click()
  const report = await download
  expect(report.suggestedFilename()).toMatch(/^ai-costs-demo-.*\.csv$/)
  const csv = await readFile((await report.path())!, 'utf8')
  const rows = csv.trim().split('\r\n').slice(1)
  expect(rows.length).toBeGreaterThan(0)
  expect(rows.every(row => row.includes('"anthropic"') && row.includes('"success"'))).toBe(true)
  await page.getByPlaceholder('Сотрудник, модель или ID…').fill('does-not-exist')
  await expect(page.getByText('Запросы не найдены')).toBeVisible()
  expect(errors).toEqual([])
})

test('creates a key, changes budget and quarantines an employee', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Сотрудники и ключи' }).click()
  await page.getByRole('button', { name: 'Добавить сотрудника', exact: true }).click()
  await page.getByLabel('Имя и фамилия').fill('Тестовый Сотрудник')
  await page.getByLabel('Рабочий email').fill('test@example.com')
  await page.getByLabel('Отдел', { exact: true }).last().fill('Аналитика')
  await page.getByLabel('Лимит в месяц, USD').fill('25')
  await page.getByRole('button', { name: 'Создать ключ', exact: true }).click()
  await expect(page.locator('.key-box')).toContainText('act_demo_')
  await page.getByRole('button', { name: 'Готово', exact: true }).click()
  await page.getByPlaceholder('Имя, email или VPN IP…').fill('test@example.com')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await expect(page.locator('tbody tr')).toContainText('10.10.9.7/24')
  await page.getByRole('button', { name: 'Настройки: Тестовый Сотрудник' }).click()
  await page.getByLabel('Месячный лимит, USD').fill('40')
  await page.getByLabel('VPN IP с маской').fill('10.10.9.8/24')
  await page.getByRole('button', { name: 'Сохранить настройки' }).click()
  await expect(page.locator('tbody tr')).toContainText('$40')
  await expect(page.locator('tbody tr')).toContainText('10.10.9.8/24')
  await page.getByRole('button', { name: 'Активен', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Карантин', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Карантин', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Активен', exact: true })).toBeVisible()
})

test('opens an employee AI usage dashboard with models, tokens, cost and time', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Использование сотрудников', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Использование: Анна Смирнова.' })).toBeVisible()
  await expect(page.getByLabel('Сотрудник', { exact: true })).toHaveValue('demo-0')
  await expect(page.getByRole('region', { name: 'Показатели сотрудника Анна Смирнова' })).toContainText('Всего токенов')
  await expect(page.getByRole('heading', { name: 'Использованные модели' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Запросы Анна Смирнова' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Время ответа' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Всего токенов' })).toBeVisible()
})

test('mobile layout fits and navigation works', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Обзор расходов.' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Открыть меню' }).click()
  await page.getByRole('button', { name: 'Использование сотрудников', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Использование: Анна Смирнова.' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Открыть меню' }).click()
  await page.getByRole('button', { name: 'Настройки', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Тарифы моделей' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
